### ISSUE TITLE
Import doesn't work (HTTP Error 410: Gone)

### ISSUE THREAD

**Issue by jeevatkm** [IQAndreas/github-issues-import#10]
Import issues is not working when source and target repo name is similar on forked repo. Throws an error.

**For example:**
Source: xxxxxx/SampleRepo
Target: yyyyyy/SampleRepo

**Error Log:**

<pre><code>Traceback (most recent call last):
  File "gh-issues-import.py", line 307, in <module>
    import_all_open_issues()
  File "gh-issues-import.py", line 297, in import_all_open_issues
    return import_issues(issues)
  File "gh-issues-import.py", line 184, in import_issues
    known_milestones = get_milestones(target_url)
  File "gh-issues-import.py", line 116, in get_milestones
    return send_get_request("%s/milestones?state=open" % url)
  File "gh-issues-import.py", line 111, in send_get_request
    response = urllib.request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
</code></pre>

**Comment by jeevatkm** [comment]
@IQAndreas - Reslove it by enabling Issues setting in Forked Repo.

Steps I followed:
- Go to the Settings page of your forked repo
- Check the box next to Issues

Then executed your script :) Issues import successful.

Cheers,
Jeeva
